// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from 'next/dynamic'

export const components = {
  customer: dynamic(() => import('./Customer')),
  gallery: dynamic(() => import('./Gallery')),
  home_content: dynamic(() => import('./HomeContent')),
  skill_description: dynamic(() => import('./SkillDescription')),
}
