// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from 'next/dynamic'

export const components = {
  home_content: dynamic(() => import('./HomeContent')),
  skills_descriptions: dynamic(() => import('./SkillsDescriptions')),
}
