// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from 'next/dynamic'

export const components = {
	about: dynamic(() => import('./About')),
	experience: dynamic(() => import('./Experience')),
	info_header: dynamic(() => import('./InfoHeader')),
	projects: dynamic(() => import('./Projects')),
}
